### ISSUE TITLE
Add applicants contact information in list view and allow setting status in list view

### ISSUE THREAD

**Issue by eivinhj** [NTNUI/opptak#126]
To simplify the process of contacting people to schedule interviews and to get an overview of all participants (and their statuses), it would be beneficial to have this information shown in the applications list view. Also, it would be beneficial to be able to change the applicants status here.

![image](https://user-images.githubusercontent.com/36069010/189518974-42e575fe-9b8e-4ab9-92bb-4f42f4e61e5d.png)

**Comment by Shomlings** [comment]
Agree! It was a pain at the end of the admission to go thru all the applicants to check the status to make sure we didn't miss any.  Also could it be a good idea to add a "copy to clipboad" button next to the email?

**Comment by Xtrah** [comment]
This would require a filter/selection on which committee status should be visible, as a user can have access to multiple committees' applications, such as the election committee who can see all applications.
