### ISSUE TITLE
Add "copy to clipboard" button next to emails

### ISSUE THREAD

**Issue by Xtrah** [NTNUI/opptak#128]
_Originally posted by @Shomlings in https://github.com/NTNUI/opptak/issues/126#issuecomment-1242987822_

Next to emails in the application list or in the application detail view, there should be a copy to clipboard button.

**Comment by Xtrah** [comment]
[CopyButton | Mantine](https://mantine.dev/core/copy-button/) will probably do the trick!

**Comment by LiviaValenti** [comment]
It can do the trick if we upgrade the package ❤️ ✨
