### ISSUE TITLE
Add tooltip to application text box

### ISSUE THREAD

**Issue by Xtrah** [NTNUI/opptak#88]
Add an `NtnuiInfoTooltip` tooltip to the application text box with the following help text:

```
Nyttige ting å vite er for eksempel alder, klasse, studieretning, erfaring...
```

**Comment by LiviaValenti** [comment]
1. Perhaps the description-section of the textfield can be utilized for this instead? 

![image](https://user-images.githubusercontent.com/54808860/172860397-426401eb-d31b-4480-933c-a2f72b65db80.png)

2. Do you have an alternate formulation? What do you think about the suggestion above? 

3. How should this be handled regarding several text-fields (when main board + is chosen)

![image](https://user-images.githubusercontent.com/54808860/172860584-4e036c82-98b4-41df-9ffe-ad9ab7fcf9e1.png)
